export const SHEETS_CSV_IMPORT_EXPORT_PLUGIN = "SHEETS_CSV_IMPORT_EXPORT_PLUGIN";

export const CSV_IMPORT_EXPORT_UI_PLUGIN_CONFIG_KEY = "CSV_IMPORT_EXPORT_UI_PLUGIN_CONFIG_KEY";

export const CSV_FILE_EXTENSION = ".csv";
export const CSV_CONTENT_TYPE = "text/csv;charset=utf-8";
